import "@/styles/globals.css";
import Head from "next/head";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import store from "@/store";
import setAuthToken from "@/utils/setAuthToken";
import Tostify from "@/components/utils/Tostify";

const inter = Inter({ subsets: ["latin"] });

export default function App({ Component, pageProps }) {
  if (typeof window !== "undefined") {
    const token = localStorage.getItem("token");
    if (token) {
      setAuthToken(token);
    }
  }

  return (
    <>
      <Head>
        <meta name="description" content="Generated by rent app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Rent App</title>
      </Head>
      <div
        className={`bg-gray-50 text-indigo-900 overflow-x-hidden ${inter.className}`}
      >
        <Provider store={store}>
          <Tostify />
          <Component {...pageProps} />
        </Provider>
      </div>
    </>
  );
}
