export const BOOK_PRODUCT = "BOOK_PRODUCT";
export const BOOK_PRODUCT_ERROR = "BOOK_PRODUCT_ERROR";

export const GET_BOOK_PRODUCT = "GET_BOOK_PRODUCT";
export const GET_BOOK_PRODUCT_ERROR = "GET_BOOK_PRODUCT_ERROR";

export const DELETE_BOOK_PRODUCT = "DELETE_BOOK_PRODUCT";
export const DELETE_BOOK_PRODUCT_BOOK_PRODUCT_ERROR =
  "DELETE_BOOK_PRODUCT_BOOK_PRODUCT_ERROR";

export const UPDATE_BOOK_PRODUCT = "UPDATE_BOOK_PRODUCT";
export const UPDATE_BOOK_PRODUCT_ERROR = "UPDATE_BOOK_PRODUCT_ERROR";
