export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

export const CASH_CREATE_ORDER = "CASH_CREATE_ORDER";
export const CASH_CREATE_ORDER_ERROR = "CASH_CREATE_ORDER_ERROR";

export const GET_ORDER = "GET_ORDER";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";

export const GET_MY_ORDER = "GET_MY_ORDER";
export const GET_MY_ORDER_ERROR = "GET_MY_ORDER_ERROR";