export const REGISTER = " CUSTOMER_REGISTER";
export const REGISTER_ERROR = "CUSTOMER_REGISTER_ERROR";

export const ISAUTHENTICATE = "ISAUTHENTICATE";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_MYACCOUT = "GET_MYACCOUT";
export const GET_MYACCOUT_ERROR = "GET_MYACCOUT_ERROR";
