export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";