export const ISAUTHENTICATE = "ISAUTHENTICATE";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_MYACCOUT = "GET_MYACCOUT";
export const GET_MYACCOUT_ERROR = "GET_MYACCOUT_ERROR";

export const GET_USERS = "GET_USERS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const DELETE_USERS = "DELETE_USERS";
export const DELETE_USERS_ERROR = "DELETE_USERS_ERROR";
